name: Update README with Dynamic Content

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 0 * * *'
  
  # Allows manual trigger from the Actions tab
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Update README
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python update_readme_advanced.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "🤖 Update README with latest GitHub activity"
        git push
